vexide/vexide

- packages/vexide-devices/src/screen.rs
- packages/vexide-panic/Cargo.toml
- packages/vexide-panic/src/lib.rs
Implements panicking using only vex-sdk. Some other changes were made to panic behavior though. When using the display_panics feature the program will not exit on panic and will instead loop indefinitely.
> refactor: implement panic handler with vex-sdk

- packages/vexide-devices/src/adi/analog.rs
- packages/vexide-devices/src/adi/digital.rs
- packages/vexide-devices/src/adi/linetracker.rs
- packages/vexide-devices/src/adi/mod.rs
- packages/vexide-devices/src/adi/motor.rs
- packages/vexide-devices/src/adi/pwm.rs
- packages/vexide-devices/src/adi/solenoid.rs
Ports the following ADI device APIs from `pros-rs`:
- `AdiLineTracker`
- `AdiMotor`
- `AdiSolenoid`
Also removes `AdiError` for now, opting to instead just use `PortError`, since other ADI errors aren't a thing anymore. In the future, i'll just do device-local errors for anything more specific rather than a general "ADI Error".
> feat: port over several missing ADI devices

- packages/vexide-startup/link/prelude.ld
This pr changes the user stack size to actually be 2 MiB instead of about and 8th of the correct size.
> fix: correct user stack length

- packages/vexide-async/Cargo.toml
- packages/vexide-core/Cargo.toml
- packages/vexide-devices/Cargo.toml
- packages/vexide-devices/src/adi/mod.rs
- packages/vexide-devices/src/adi/ultrasonic.rs
- packages/vexide-panic/Cargo.toml
- packages/vexide-startup/Cargo.toml
- Adds initial support for AdiUltrasonic sensors.
- Updates to `vex-sdk` 0.11.0.
- Fixes a critical bug in `validate_expander` resulting in port 21 being validated rather than port 22.
- Tested on a V5 brain. Not sure if the units for it are right, but they're what the PROS docs claim are correct.
> feat: AdiUltrasonic (and other miscellaneous ADI fixes)

- packages/vexide-core/src/io/mod.rs
- packages/vexide-core/src/io/stdio.rs
- packages/vexide-core/src/lib.rs
- packages/vexide-core/src/program.rs
- packages/vexide-panic/src/lib.rs
- packages/vexide-startup/src/lib.rs
This PR adds a exit function to vexide-startup which blocks for 3ms to flush the serial buffer and then exits the program with `vexSystemExitRequest`.
> fix: flush serial buffer on program exit

- packages/vexide-async/Cargo.toml
- packages/vexide-core/Cargo.toml
- packages/vexide-devices/Cargo.toml
- packages/vexide-devices/src/adi/accelerometer.rs
- packages/vexide-devices/src/adi/analog.rs
- packages/vexide-devices/src/adi/digital.rs
- packages/vexide-devices/src/adi/light_sensor.rs
- packages/vexide-devices/src/adi/line_tracker.rs
- packages/vexide-devices/src/adi/mod.rs
- packages/vexide-devices/src/adi/motor.rs
- packages/vexide-devices/src/adi/potentiometer.rs
- packages/vexide-devices/src/adi/pwm.rs
- packages/vexide-devices/src/adi/solenoid.rs
- packages/vexide-devices/src/adi/ultrasonic.rs
- packages/vexide-devices/src/smart/distance.rs
- packages/vexide-devices/src/smart/expander.rs
- packages/vexide-devices/src/smart/imu.rs
- packages/vexide-devices/src/smart/link.rs
- packages/vexide-devices/src/smart/mod.rs
- packages/vexide-devices/src/smart/motor.rs
- packages/vexide-devices/src/smart/optical.rs
- packages/vexide-devices/src/smart/rotation.rs
- packages/vexide-devices/src/smart/serial.rs
- packages/vexide-devices/src/smart/vision.rs
- packages/vexide-panic/Cargo.toml
- packages/vexide-startup/Cargo.toml
- packages/vexide/Cargo.toml
- Makes all device constructors infallible by ensuring safe recovery from disconnects after construction.
- Refactors internal error handling and SDK communication to (hopefully) make things simpler.
- Adds support for hotplugging device types by allowing conversion from a `SmartDevice` back into a `SmartPort` (by consuming the device).
- `RadioLink` cannot be made infallible, since it needs to establish a connection upon device creation.
- `OpticalSensor` now only enables gesture detection mode the first time `last_gesture` was called, rather than giving the option to the user.
- `VisionSensor` can no longer take a `mode` in `VisionSensor::new`, since that data gets wiped when its unplugged.
- All ADI devices attempt to configure the port before accessing the SDK in the event that the …
> refactor: device error handling

- packages/vexide-devices/src/screen.rs
This PR adds support for double buffered screen rendering by adding a `RenderMode` enum and methods to set the screens render mode.
> feat: double-buffered screen rendering support

- packages/vexide-macro/Cargo.toml
- packages/vexide-macro/src/lib.rs
- packages/vexide-startup/Cargo.toml
- packages/vexide-startup/src/lib.rs
- packages/vexide/Cargo.toml
- packages/vexide/src/lib.rs
Moves the main proc macro attribute into a new crate `vexide-macro` which is a optional dependency of vexide. This also fixes the issue where you would have to add many crates to your dependencies to get the macro to work 
> fix: get main macro working with only vexide as a dependency

- packages/vexide-core/Cargo.toml
This PR completely removes the `critical-section` feature from vexide-core because the critical-section implementation is necessary for vexide-core internally.
This PR fixes #32.
> fix: remove critical-section feature

- packages/vexide-core/src/lib.rs
- packages/vexide-core/src/program.rs
- packages/vexide-macro/src/lib.rs
This PR adds the `vexide_core::program::Termination` trait and allows the main function to return it. It also fixes a broken cfg related to the critical-section implementation
> feat: support multiple main function return types with `vexide_core::program::Termination`

- packages/vexide-devices/src/screen.rs
This fixes an issue where all text would be drawn 1 line below where it was supposed to be, unless it did not end in "\n".
- I have tested these changes in a simulator.
Test program:
```rs
#[vexide::main]
async fn main(peripherals: Peripherals) {
let mut p = peripherals;
writeln!(p.screen, "Hello, world.").unwrap();
writeln!(p.screen, "Hello, world {:?}", 2).unwrap();
loop {}
}
```
> fix(screen): flush before advancing lines

- packages/vexide-core/src/critical_section.rs
This fixes an issue where the critical-section implementation was looking at the wrong bit in CPSR as well as the release function not enabling interrupts at the correct time. 
> fix: use correct bit for IRQ status flag

- packages/vexide-core/src/competition.rs
Refactors the way that competition tasks are created to support running in driver mode while not connected to a competition controller.
Closes #29
> fix: competition API while disconnected

- packages/vexide-devices/src/smart/distance.rs
- packages/vexide-devices/src/smart/imu.rs
- packages/vexide-devices/src/smart/link.rs
- packages/vexide-devices/src/smart/motor.rs
- packages/vexide-devices/src/smart/optical.rs
- packages/vexide-devices/src/smart/rotation.rs
- packages/vexide-devices/src/smart/serial.rs
- packages/vexide-devices/src/smart/vision.rs
Smart devices are currently not `Send` or `Sync`, which makes them not shareable between async tasks. This is because we store a raw device handle `V5_DeviceT` for convenience when interacting with the SDK. Sending raw pointers across threads isn't inherently unsound, and the lack of `Send + Sync` on raw pointers exists more as a lint.
> fix: implement `Send` and `Sync` for smart devices

- packages/vexide/src/lib.rs
Minor fixes in lib.rs docs to remove some inaccurate/duplicated advantages over PROS.
* PROS is also actively developed, so that is not an advantage here
* vexide being a crate was mentioned twice
> docs: update advantages over PROS to eliminate duplicate and inaccurate points

- packages/vexide-devices/src/controller.rs
This PR updates the controller struct to use the correct axes so that the correct values will be returned when calling Joystick methods.
> fix(controller): use correct axes for left and right sticks

- packages/vexide-core/src/program.rs
Changes several `pub use`s to normal `use` in `program.rs` to avoid unintentionally exposing vex-sdk functions as well as some random types from the `time` module.
> fix: remove several unintended `pub use`s from `program.rs`

- packages/vexide-devices/src/adi/encoder.rs
Brings it inline with other devices returning `Position`.
> feat: add ticks per revolution constant to `AdiEncoder`

- CHANGELOG.md
- packages/vexide-async/Cargo.toml
- packages/vexide-core/Cargo.toml
- packages/vexide-devices/Cargo.toml
- packages/vexide-graphics/Cargo.toml
- packages/vexide-math/Cargo.toml
- packages/vexide-panic/Cargo.toml
- packages/vexide-startup/Cargo.toml
- packages/vexide/Cargo.toml
This PR bumps vexide to version 0.2.0
> docs: bump version

- CHANGELOG.md
- packages/vexide-startup/Cargo.toml
- packages/vexide-startup/link/v5.ld
- packages/vexide/Cargo.toml
This PR fixes and issue with the linker script that misplaced the .boot section. Somehow this caused release builds to function and debug builds to fail.
> fix: correctly place .boot after the cold header

- packages/vexide-macro/Cargo.toml
- packages/vexide-macro/src/lib.rs
This PR updates the vexide-macro crate's codegen to wrap the original function rather than rewriting it. This fixes #74 and simplifies some of the logic for code generation. It also adds some related tests to the crate.
- See also: #74's example program
> fix(macro): wrap original function instead of re-writing

- flake.lock
- flake.nix
This pull request adds the missing development dependencies to the dev environment, the main one being cargo with the nightly toolchain. This should allow any developer loading up the nix environment to start working right away, instead of having to download additional tools.
> fix: add nightly cargo to the flake dev environment

- packages/vexide-devices/src/screen.rs
This PR fixes #71, making the widget fields public. Additionally I added documentation to the now-public fields. This should be merged because it makes extending and using the widget classes more accessible. 
I haven't tested this yet, but it seems relatively simple. I can test it this week on V5 hardware if that's needed.
> Make widget properties public and add documentation

- packages/vexide-devices/src/screen.rs
This PR adds metrics getters for text widgets using the vexDisplayString(Width/Height)Get
I haven't tested these changes, but @doinkythederp tested it and it worked
> feat: add text metrics getter

- flake.nix
This PR adds the `llvm-tools` component to the Rust toolchain in our flake. This lets you use cargo-pros with the flake's toolchain.
- I have tested this.
> fix: add missing llvm-tools component to rust toolchain in flake

- packages/vexide-devices/src/screen.rs
This pr adds a text alignment feature to Text widgets using the .width and .height methods
Can't test this today, but I can tomorrow
> feat: Add text alignment to Text widget

- packages/vexide-devices/Cargo.toml
- packages/vexide-devices/src/geometry/mod.rs
- packages/vexide-devices/src/geometry/nalgebra.rs
Adds an optional feature for converting Point2 to its corresponding `nalgebra` type. Also makes a few Point2 functions `const` and implements `IntoMint`.
> feat: add more Point2 conversions

- packages/vexide-core/src/competition.rs
- packages/vexide/examples/clawbot.rs
- packages/vexide/examples/competition.rs
- packages/vexide/src/lib.rs
- **docs: fix erroneous comment on `CompetitionRuntime._pin`**
- **refactor(competition): rename `Competition` to `Compete`**
Trait names typically take one of two forms:
1. Noun phrases describing something the type _is_ (e.g. an implementor of `SmartDevice` _is_ a smart device).
2. Verb phrases describing something the type can _do_ or something that can be _done to_ the type (e.g. an implementor of `Display` can be displayed).
With the recent merge of #87, the convenience trait for constructing a competition runtime, `Competition`, no longer follows this convention. Instead of describing competitions, `Competition` describes things (robots) which compete in competitions.
This PR renames the trait to `Compete` to maintain the brevity of `Competition`, but stick to established …
> refactor: rename `Competition` trait to `Compete`

- .github/workflows/rust.yml
- .vscode/settings.json
- CHANGELOG.md
- packages/vexide-macro/Cargo.toml
- packages/vexide-macro/src/lib.rs
- packages/vexide-macro/src/parse.rs
- packages/vexide-startup/Cargo.toml
- packages/vexide-startup/examples/booting.rs
- packages/vexide-startup/src/lib.rs
- packages/vexide/examples/bannerless.rs
- packages/vexide/examples/custom_code_sig.rs
This PR moves the option for toggling the vexide ASCII art banner into the parameters of the main macro to make it easier to disable. It fixes #97. It also adds a way to use a custom code signature.
This likely does not come at a code size cost compared to disabling the banner with the feature because it uses const generics to toggle the banner, but I haven't gotten to profiling yet.
> feat: add startup options to main macro

- packages/vexide/examples/clawbot.rs
This PR fixes a bug in the clawbot example that prevents the arm from moving while the claw is not being controlled.
> fix(clawbot): enable arm usage when claw is not in use

- packages/vexide-startup/link/v5.ld
Fixes a memory error in the new linkerscript that triggers during heap allocation. 
No idea why that happened, but only including `rodata1` in our sections fixes it.
> fix: heap allocation memory errors

- CHANGELOG.md
- packages/vexide-devices/src/smart/distance.rs
- packages/vexide/examples/smart_devices.rs
Updates the Distance Sensor API to return None on invalid distance and adds a more informative error code. 
Fixes: #94
- These (might be) are breaking changes (semver: major).
> feat: update distance sensor API to return none on a invalid distance 

- CHANGELOG.md
- packages/vexide-devices/src/smart/distance.rs
This PR accounts for invalid relative size values in the Distance Sensor API.
Needs testing.
> fix: check for negative relative_size results

- CHANGELOG.md
- packages/vexide-devices/src/adi/accelerometer.rs
- packages/vexide-devices/src/adi/addrled.rs
- packages/vexide-devices/src/adi/analog.rs
- packages/vexide-devices/src/adi/digital.rs
- packages/vexide-devices/src/adi/encoder.rs
- packages/vexide-devices/src/adi/light_sensor.rs
- packages/vexide-devices/src/adi/line_tracker.rs
- packages/vexide-devices/src/adi/mod.rs
- packages/vexide-devices/src/adi/motor.rs
- packages/vexide-devices/src/adi/potentiometer.rs
- packages/vexide-devices/src/adi/pwm.rs
- packages/vexide-devices/src/adi/range_finder.rs
- packages/vexide-devices/src/adi/solenoid.rs
- packages/vexide-devices/src/peripherals.rs
- packages/vexide-devices/src/smart/distance.rs
- packages/vexide-devices/src/smart/expander.rs
- packages/vexide-devices/src/smart/gps.rs
- packages/vexide-devices/src/smart/imu.rs
- packages/vexide-devices/src/smart/link.rs
- packages/vexide-devices/src/smart/mod.rs
- packages/vexide-devices/src/smart/motor.rs
- packages/vexide-devices/src/smart/optical.rs
- packages/vexide-devices/src/smart/rotation.rs
- packages/vexide-devices/src/smart/serial.rs
- packages/vexide-devices/src/smart/vision.rs
- For historical reasons, `SmartPort::device_type` returned `Result` even though it could never fail (`SmartDeviceType` -> `V5_DeviceType` used to be `TryFrom`). This PR fixes that.
- Renames all terminology of 1-indexed port numbers to be `number` rather than index, and renames all 0-index terminology to be `index`. This matches up terminology with recent simulator APIs (which more heavily lean to use `index` than number due to being SDK-internal).
> refactor: consistent port numbering terminology, infallible `SmartPort::device_type`

- CHANGELOG.md
- packages/vexide-async/src/time.rs
- packages/vexide-core/src/sync/barrier.rs
- packages/vexide-core/src/sync/condvar.rs
- packages/vexide-core/src/sync/mutex.rs
- packages/vexide-core/src/sync/rwlock.rs
- packages/vexide-devices/src/smart/imu.rs
This PR adds a warning when `sleep()` futures are discarded without being used - this is likely unintentional as the function itself has no side-effects.
> feat: add must_use to Sleep struct

- CHANGELOG.md
- packages/vexide-devices/src/screen.rs
Fixes the region passed to vexDisplayCopyRect in the Screen struct.
> fix(screen): correct vexDisplayCopyRect region

- CHANGELOG.md
- packages/vexide-panic/src/lib.rs
This PR fixes a bug where enabling screen double buffering would stop graphical panic messages from being displayed on the screen.
Closes #92 
> fix: stop double buffered rending from stopping panic message rendering

- CHANGELOG.md
- packages/vexide-async/Cargo.toml
- packages/vexide-core/Cargo.toml
- packages/vexide-devices/Cargo.toml
- packages/vexide-devices/src/smart/gps.rs
- packages/vexide-devices/src/smart/mod.rs
- packages/vexide-graphics/Cargo.toml
- packages/vexide-panic/Cargo.toml
- packages/vexide-startup/Cargo.toml
- packages/vexide/Cargo.toml
As of `vex_sdk` 0.20.0, `V5_Device` is now an entirely opaque type, due to possible incorrectness regarding the memory layout of the reverse-engineered fields on that struct and due to possible instability of that internal struct across firmware updates. This PR removes any dereferences of `V5_Device` to try to read one of those fields with a public SDK function. The most common occurance of this was when trying to get a device handle's type, which has been replaced by a call to `vexDeviceGetStatus` - a function that returns the connection type of every port on the brain. This is the same method used by VDML in PROS, meaning it should be more theoretically sound than what we were doing before.
This also caused me to find an off-by-one error in `GpsImu` which has also been fixed.
- Bumps …
> refactor: avoid dereferencing `V5_DeviceT` at all cost

- CHANGELOG.md
- packages/vexide-async/Cargo.toml
- packages/vexide-core/Cargo.toml
- packages/vexide-devices/Cargo.toml
- packages/vexide-graphics/Cargo.toml
- packages/vexide-macro/Cargo.toml
- packages/vexide-panic/Cargo.toml
- packages/vexide-startup/Cargo.toml
- packages/vexide-startup/src/banner/mod.rs
- packages/vexide/Cargo.toml
Updates vexide versions to 0.4.0 for the upcoming release. The tag v0.4.0 will be created on merge.
> chore: bump version

- packages/vexide-async/Cargo.toml
This PR fixes an outdated category slug in vexide-async.
> fix: rename Asynchronous category to asynchronous

- CHANGELOG.md
- Cargo.toml
- packages/vexide-async/Cargo.toml
- packages/vexide-core/Cargo.toml
- packages/vexide-devices/Cargo.toml
- packages/vexide-graphics/Cargo.toml
- packages/vexide-panic/Cargo.toml
- packages/vexide-startup/Cargo.toml
This PR updates the vex-sdk dependency and all vexide crates.
The tag v0.4.1 will be created on merge.
> chore: bump vexide and update vex-sdk dep

- CHANGELOG.md
- examples/clawbot.rs
- examples/pneumatics.rs
- examples/smart_devices.rs
- examples/split_arcade_drive.rs
- examples/tank_drive.rs
- packages/vexide-devices/src/controller.rs
This PR refactors the controller API so that all controller state is returned at once. A single controller channel cannot error without every other controller channel erroring, so this removes all unnecessary error handling.
Closes #131 
> refactor: switch to an all in one controller state getter

- Cargo.toml
- packages/vexide-async/Cargo.toml
- packages/vexide-core/Cargo.toml
- packages/vexide-devices/Cargo.toml
- packages/vexide-graphics/Cargo.toml
- packages/vexide-macro/Cargo.toml
- packages/vexide-panic/Cargo.toml
- packages/vexide-startup/Cargo.toml
- packages/vexide/Cargo.toml
This PR should fix any possible issues with pros.rs docs builds.
should close #162 
> fix: build docs to target supporting vex-sdk calling convention

- CHANGELOG.md
- examples/clawbot.rs
- examples/smart_devices.rs
- examples/split_arcade_drive.rs
- examples/tank_drive.rs
- packages/vexide-devices/src/smart/motor.rs
This PR adds support for 5.5W Smart motors. This entails:
- a new constructor for `Motor`:`Motor::new_exp`.
- new motor type getters: `Motor::motor_type`, `Motor::is_v5`, `Motor::is_exp`.
- split `Motor::MAX_VOLTAGE` into `Motor::MAX_VOLTAGE_V5` and `Motor::MAX_VOLTAGE_EXP`.
Closes #140.
> feat: add support for 5.5W motors

- CHANGELOG.md
- packages/vexide-devices/src/smart/distance.rs
- packages/vexide-devices/src/smart/expander.rs
- packages/vexide-devices/src/smart/gps.rs
- packages/vexide-devices/src/smart/imu.rs
- packages/vexide-devices/src/smart/link.rs
- packages/vexide-devices/src/smart/mod.rs
- packages/vexide-devices/src/smart/motor.rs
- packages/vexide-devices/src/smart/optical.rs
- packages/vexide-devices/src/smart/rotation.rs
- packages/vexide-devices/src/smart/serial.rs
- packages/vexide-devices/src/smart/vision.rs
Fixes an issue where `SmartPort`s could be duplicated through a bad from implementation on any type implementing `SmartDevice`.
Closes #170 
> fix: implement into smartport seperately for every smart device

- packages/vexide-devices/src/controller.rs
Removes an unsafe block by using `as_ptr()` instead of `into_raw()`.
> refactor(ControllerScreen): use as_ptr instead of into_raw

- packages/vexide-core/src/io/stdio.rs
This PR uses the `file!` and `line!` macros correctly in the `dbg!` macro's empty arm.
Fixes #173.
- I _haven't_ tested these changes on a VEX V5 brain. (My school is on break and I don't have access to the hardware now)
> fix(core): use correct file/line macro in dbg!()

- packages/vexide-devices/src/controller.rs
Based on the way its used, it should be `[-127, 127]`.
> docs: fix raw joystick getter range comment

- CHANGELOG.md
- packages/vexide-devices/src/adi/accelerometer.rs
- packages/vexide-devices/src/adi/potentiometer.rs
- packages/vexide-devices/src/smart/motor.rs
- packages/vexide-devices/src/smart/rotation.rs
Changes several device getters that do not interact with hardware to be infallible.
Closes #172 
> fix: make getters that do not access hardware infallible

- packages/vexide-devices/src/controller.rs
`was_pressed` field needs to initialise as true, otherwise the initial call of `was_pressed()` will return true even if the button hasn't been touched.
fixes the behaviour of was_pressed in vexide 0.4.2.
> bugfix: controller: fixed initial was_pressed

- CHANGELOG.md
- Cargo.toml
- packages/vexide-devices/src/smart/motor.rs
This PR fixes an issue where `Motor::velocity` did not actually return the estimated velocity.
This is blocking on an update to vex-sdk that fixes the absolute velocity sdk call address.
> fix: use correct motor velocity getter

- packages/vexide-devices/src/smart/motor.rs
> fix: use correct max voltage for 5.5w motor

- CHANGELOG.md
- packages/vexide-devices/src/smart/optical.rs
This is a bit of a bikeshed, but I think these method names are a lot more clear in what they do. They also line up better with the naming of other methods with `raw` counterparts.
> refactor: rename `OpticalSensor::rgb` -> `color` and `raw` -> `raw_color`

- CHANGELOG.md
- packages/vexide-devices/src/controller.rs
Adds a getter to retrieve a controller's ID. This is useful for debugging and logging as it provides users with more information about the controller.
> feat: add controller ID getter

- packages/vexide-core/src/float/newlib.rs
Fixes some warnings that will become errors in Rust 2024.
> fix: improve rust 2024 compat

- packages/vexide-core/src/program.rs
Our current exit behavior has the possibility of freezing the CPU if we're compiling for a single-core target like EXP, since VEXos would get no time to handle a `vexSystemExitRequest`. This PR fixes that by calling `vexTasksRun` while waiting for the exit request to complete and also cleans up some docs around it.
> fix: program exit behavior on single-core targets

- packages/vexide-devices/src/peripherals.rs
This PR adds the ability to return ports to an instance of `DynamicPeripherals`, as well as adding support for controllers which was not possible previously. It has also been refactored to not use any unsafe code and uses `Option`s as cells instead of `bool`s.
> feat: return ports to DynamicPeripherals

- CHANGELOG.md
- packages/vexide-devices/src/adi/addrled.rs
Does what it says in the title.
Closes #191.
> fix: remove useless generics from `AdiAddrLed::new`

- CHANGELOG.md
- packages/vexide-devices/src/adi/addrled.rs
> refactor: rename `AddrLedError::Adi` to `AddrLedError::Port`

- CHANGELOG.md
- packages/vexide-devices/src/smart/serial.rs
- Added a `SerialPort::set_baud_rate` method for the adjusting baudrate of a generic serial smartport after initialization.
- `SerialPort::read_byte` now takes `&mut self`. 
Closes #216.
> feat: `SerialPort::set_baud_rate`, `read_byte` mutability

- CHANGELOG.md
- packages/vexide-devices/src/adi/mod.rs
- packages/vexide-devices/src/smart/mod.rs
- Removed `SmartDeviceType::None`.
- `SmartPort::device_type` now returns an `Option<SmartDeviceType>` which returns `None` if no device is connected or configured to a port.
- Refactored some internal details of port validation.
> refactor: remove `SmartDeviceType::None`, refactor port validation

- packages/vexide-devices/src/smart/electromagnet.rs
- packages/vexide-devices/src/smart/serial.rs
- Removes `unwrap` calls in electromagnet examples.
- Adds mutability to electromagnet instance in examples that require it.
- Adds an example for `SerialPort::set_baud_rate`.
> docs: fix electromagnet examples, add `SerialPort::set_baud_rate` exampe

- CHANGELOG.md
- Cargo.toml
- packages/vexide-async/Cargo.toml
- packages/vexide-core/Cargo.toml
- packages/vexide-devices/Cargo.toml
- packages/vexide-graphics/Cargo.toml
- packages/vexide-panic/Cargo.toml
- packages/vexide-startup/Cargo.toml
- packages/vexide/Cargo.toml
I did bad things cause I forgor about the 0.4.2 branch. rc1 still works but its cursed so this should fix it.
> fix: correctly bump versions

- CHANGELOG.md
- packages/vexide-devices/src/position.rs
This PR simply adds some implementations for scaling `Position` instances which are helpful for e.g. computing averages.
This PR in theory still maintains the "opaqueness" of the `Position` type since it just allows scaling and not any other operations. This still might not be what you want; if you don't like it, feel free to close the PR.
- semver: minor
- Closes #229
> feat: add `Mul<i64>` and `Div<i64>` impls for `Position`

- CHANGELOG.md
- examples/panic_hook.rs
- packages/vexide-panic/src/lib.rs
This change allows the panic handler to be overridden by the user in a manner similar to the Rust standard library: using `set_hook` and `take_hook`.
- Supersedes #118 and #233
(Note the red background behind the popup, which isn't present by default. This is a photo from the `panic_hook` example)
> Panic Hooks v3

- CHANGELOG.md
- packages/vexide-devices/src/controller.rs
Adds support for detecting if the center power button is pressed through the `Controller` API. Name can be bikeshedded if necessary, but i'm just going with `button_power` for now to match the rest.
> feat: power button support in `Controller`

- packages/vexide-panic/src/lib.rs
#234 broke some people's CI because it didn't return `!` to the panic handler if `display_panics` was not enabled. Now it does.
This is a bugfix.
> fix(panic): remove feature gate which shouldn't exist

- CHANGELOG.md
- packages/vexide-devices/src/position.rs
`Position`-to-`Position` `Mul`/`Div` operations are mathematically unsound due to such operations creating a new dimension (specifically a [Steradian](https://en.wikipedia.org/wiki/Steradian), which is representible as m^2/m^2). This PR removes such operations and only allows `Angle {+, -} Angle` and `Angle {*, /} Scalar`
> fix: remove `Position`-to-`Position` `Mul`/`Div` ops

- CHANGELOG.md
- packages/vexide-devices/src/smart/gps.rs
- packages/vexide-devices/src/smart/link.rs
- `GpsSensor::new` is now infallible.
- `RadioLink::open` no longer validates ports (this was causing panics since VEXos reconfigures a radio link as generic serial) and can only return `Nul`.
Hardware tested
> refactor: adjust fallibility of `GpsSensor` & `RadioLink`

- CHANGELOG.md
- Cargo.toml
- examples/README.md
- examples/vexlink_manager.rs
- examples/vexlink_worker.rs
- packages/vexide-async/Cargo.toml
- packages/vexide-core/Cargo.toml
- packages/vexide-devices/Cargo.toml
- packages/vexide-devices/src/smart/link.rs
- packages/vexide-graphics/Cargo.toml
- packages/vexide-panic/Cargo.toml
- packages/vexide-startup/Cargo.toml
- packages/vexide/Cargo.toml
- Removes port validation from VEXlink radios. Once a `RadioLink` is opened, VEXos will reconfigure the radio's smartport as generic serial, making it impossible to do any validation (the port will continue to report a `GenericSerial` connected_type even if no device is plugged in). This also caused a panic on second run, since serial configuration lasts across program runs.
- `available_write_bytes` now correctly handles its errors in the event of a -1 return. This prompted an update to `vex-sdk` 0.25.2, which relies on multiple breaking changes in our target spec. Oh well.
> fix: correctly handle VEXlink errors

- packages/vexide-core/src/sync/mutex.rs
- packages/vexide-core/src/sync/rwlock.rs
This PR adds some attributes to Mutex and RwLock guards that make some clippy lints more useful and mirrors `std` and `parking_lot`'s implementations.
- These are *only* non-code changes. (Well, they  _are_ code changes, but they're documentation code changes.)
- Fixes #244
> feat: add `#[clippy::has_significant_drop]` and `#[must_use]` attributes to `vexide_core::sync`

- CHANGELOG.md
- packages/vexide-core/src/sync/rwlock.rs
`Send` and `Sync` implementations were not created for `RwLock`, making the lock essentially useless in Rust's type system.
This PR also updates the generic `T` in `RwLock` to be `?Sized` for more flexibility.
- I haven't tested these changes
- semver: minor/patch (you pick)
> fix(core): add `Send` + `Sync` impls for `RwLock`

- CHANGELOG.md
- packages/vexide-devices/src/adi/digital.rs
This PR adds a way to specify the initial level of a digital ADI port while creating the port. This simplifies the common use case of starting a competition with a pneumatic piston at a certain state.
- semver: minor
> feat(devices): add `with_initial_level` to `AdiDigitalOut`

- packages/vexide-devices/Cargo.toml
- packages/vexide-graphics/Cargo.toml
Enables features which add additional APIs during docs.rs builds.
This fixes (along with a couple other things) the fact that there are [no API docs at all](https://docs.rs/vexide-graphics/0.1.7/vexide_graphics/) for vexide-graphics.
> docs: show opt-in APIs on docs.rs

- CHANGELOG.md
- packages/vexide-core/src/sync/lazy.rs
- packages/vexide-core/src/sync/once.rs
Fixes #255
- Breaking changes! Major semver
- Renamed using the Rust LSP implementation!
> fix: rename Once::is_complete to is_completed

- packages/vexide-panic/src/lib.rs
The Rust 2024 clippy lints seemed to have triggered on my code. I've reviewed it and it seems that the new behavior is actually better than the old behavior. Thus, I added an `#[allow]` and a comment.
I wrote this message at 2024-12-19 21:40:42 JST.
> fix(panic): allow if_let_rescope lint for Rust 2024

- CHANGELOG.md
- packages/vexide-devices/src/adi/encoder.rs
- packages/vexide-graphics/src/embedded_graphics.rs
- packages/vexide-graphics/src/slint.rs
This PR fixes some misconceptions we had about encoder ports. VEX article summarizes it well:
Also resolves some leftover lints from the nightly update a while back.
Closes #252
> fix: encoder port validation, lint

- CHANGELOG.md
- packages/vexide-devices/src/adi/range_finder.rs
Roughly the same deal as #264. In the future, `BadOutputPort` should swap names with  `BadInputPort`, since it's now a complete misnomer.
> fix: AdiRangeFinder port validation

- CHANGELOG.md
- packages/vexide-panic/src/lib.rs
If a user-registered panic hook happens to panic itself, or a call to `println!` in our current `panic_handler` happens to panic, then we end up with a potentially recursive panic, which can result in some nasty stack overflow bugs. This ends up having some bad side-effects, such as `println!` being called in a tight loop causing a stack overflow:
```rs
loop {
println!("What");
}
```
To recap:
`println!()` -> `stdout().write_all()` -> `panic!()` (because the buffer is unabled to be flushed in a tight loop thanks to #273) -> `println!()`
This PR puts a check in place to make sure we only call the hook and proceed with the I/O portion of the panic if this is the first time `panic!` has been called. If a recursive panic occurs, we immediately abort.
> fix: abort on recursive panics

- CHANGELOG.md
- packages/vexide-devices/src/smart/imu.rs
See the discussion in #200 for a more detailed explanation of what this PR aims to fix.
**These changes have been hardware tested.**
> fix: avoid trying to reset IMU if calibration is already occurring

- CHANGELOG.md
- packages/vexide-devices/src/controller.rs
- packages/vexide-devices/src/display.rs
- packages/vexide-devices/src/smart/ai_vision.rs
- packages/vexide-devices/src/smart/vision.rs
- packages/vexide-graphics/src/slint.rs
This PR refactors most of the error variants in device errors caused by user end bugs into panics.
> Functions often have contracts: their behavior is only guaranteed if the inputs meet particular requirements. Panicking when the contract is violated makes sense because a contract violation always indicates a caller-side bug, and it’s not a kind of error you want the calling code to have to explicitly handle.
> refactor: turn errors caused by user end bugs into panics

- CHANGELOG.md
- packages/vexide-devices/src/smart/imu.rs
When calibrating the inertial sensor, there will be a brief period at the start of the program where the sensor will report a 0x0 status code. This period can vary, and was over 20 milliseconds in my testing. When in this state, the sensor will refuse calibration and potentially miscalibrate. This PR adds a new waiting stage to `InertialCalibrateFuture` that waits until the status code is NOT 0.
Hardware Tested :D
> fix: wait until status != 0 before imu calibrate

- packages/vexide-devices/src/adi/encoder.rs
When trying to create a new AdiEncoder the program will panic and give ExpanderPortMismatch regardless if there is an Adi Expander or the encoder is plugged into valid ports. When it checks to ensure the ports are from the same Adi Expander a != is used instead of ==.
> fix: Checking for AdiExpander ports to match should be == not !=

- packages/vexide-devices/src/display.rs
A two-line change to indicate panicking behavior.
> docs(devices): update docs to communicate that `draw_buffer` panics

- CHANGELOG.md
- packages/vexide-core/src/io/stdio.rs
Prevents instantiation of `Stdout`/`Stdin` instances outside of their respective functions. This ensures we can backwards-compatibly add potential private fields to said structs.
Bad:
```rs
let wow_stdout = io::Stdout;
```
Good:
```rs
let wow_stdout = io::stdout();
```
> fix: disallow explicit construction of Stdin/Stdout

- CHANGELOG.md
- packages/vexide-core/src/competition.rs
- packages/vexide-core/src/lib.rs
- packages/vexide-core/src/os.rs
- packages/vexide-core/src/time.rs
- packages/vexide-startup/src/banner/mod.rs
This PR adds functions to vexide for getting the vexOS version and uptime.
> feat: :sparkles: Add uptime and VEXos version getters to vexide-core

- CHANGELOG.md
- examples/adi.rs
- packages/vexide-devices/src/adi/accelerometer.rs
- packages/vexide-devices/src/adi/addrled.rs
- packages/vexide-devices/src/adi/analog.rs
- packages/vexide-devices/src/adi/digital.rs
- packages/vexide-devices/src/adi/encoder.rs
- packages/vexide-devices/src/adi/gyroscope.rs
- packages/vexide-devices/src/adi/light_sensor.rs
- packages/vexide-devices/src/adi/line_tracker.rs
- packages/vexide-devices/src/adi/mod.rs
- packages/vexide-devices/src/adi/motor.rs
- packages/vexide-devices/src/adi/potentiometer.rs
- packages/vexide-devices/src/adi/pwm.rs
- packages/vexide-devices/src/adi/range_finder.rs
- packages/vexide-devices/src/adi/servo.rs
- Fixes naming of error handling variants.
- Removes unused error handling variants.
- Changed constructor functions of two-wire devices to take their ports as separate arguments rather than one tuple.
- Implements a solution for #120 by refactoring how `AdiDevice` works.
Breaking Change.
> refactor: clean up two-wire ADI devices

- packages/vexide-devices/src/adi/line_tracker.rs
This PR adds docs noting the datasheet of the ADI line tracker VEX allows. Fixes #272.
> docs(devices): add more hardware notes for line tracker

- packages/vexide-core/src/os.rs
This PR implements PartialOrd/Ord for Version, allowing VEXos versions to be compared with `>`/`<`. Closes #287
> feat: :sparkles: Implement PartialOrd/Ord for Version

- CHANGELOG.md
- packages/vexide-devices/src/controller.rs
The `vexide-devices` `Battery` API returns a float from 0.0 to 1.0 indicating the robot battery's value. For consistancy, this PR updates the controller getter to act the same way.
- Breaking change
- Needs hardware testing
> refactor(devices): update battery_capacity to return f64

- Cargo.toml
- packages/vexide/Cargo.toml
`cargo-v5` will only take metadata from the current package in the next release rather than finding the first package with metadata. This PR moves the examples metadata to the correct `Cargo.toml`.
> chore: move cargo-v5 metadata to examples package

- CHANGELOG.md
- examples/fs.rs
- packages/vexide-core/src/fs/mod.rs
This PR adds a Drop implementation to File which will close the files FD. Closing the FD also automatically flushes it.
Closes #294 
- I have tested these changes on a VEX V5 Brain.
> fix: close files on drop

- CHANGELOG.md
- examples/smart_devices.rs
- examples/vexlink_manager.rs
- examples/vexlink_worker.rs
- packages/vexide-devices/src/smart/link.rs
- packages/vexide-devices/src/smart/serial.rs
This PR addresses the concerns brought up in #277 by adding a dedicated future for `SerialPort::open` to wait until VEXos properly configures the port's uartlite for generic serial exchange. This is usually in the range of 10mS if the port wasn't previously configured in a past program run. Because we can now guarantee that the port will always be configured that way for the duration of the program, we can also remove `V5_DeviceType` validation from most of the APIs.
Additionally, i've made `RadioLink::open` panic rather than returning an error if the user passes an invalid ID containing a NUL. This is in compliance with #266. Documentation has been updated accordingly.
NOTE: `RadioLink::open` seemingly does not need a future, as it will immediately adjust the `V5_DeviceType` to …
> refactor: Asynchronous `SerialPort` opening, infallible VEXlink opening

- CHANGELOG.md
- packages/vexide-core/src/allocator.rs
- packages/vexide-core/src/fs/fs_str.rs
- packages/vexide-core/src/fs/mod.rs
- packages/vexide-core/src/io/mod.rs
- packages/vexide-core/src/io/stdio.rs
- packages/vexide-devices/src/adi/gyroscope.rs
- packages/vexide-devices/src/adi/mod.rs
- packages/vexide-devices/src/adi/servo.rs
- packages/vexide-devices/src/controller.rs
- packages/vexide-devices/src/display.rs
This PR makes the printing macros flush the serial buffer if it would be overflowed by the write.
I also fixed some docs issues along the way.
TODO:
- I have tested these changes on a VEX V5 Brain.
> fix: implement naive print macro flushing

- CHANGELOG.md
- packages/vexide-devices/src/adi/encoder.rs
See https://github.com/purduesigbots/pros/blob/develop-pros-4/src/devices/vdml_ext_adi.c#L113
`AdiRangeFinder` should be unaffected due to us already asserting the output port being below the input.
> fix: `AdiEncoder` port misconfiguration case

- CHANGELOG.md
- examples/fs.rs
- examples/sync.rs
- packages/vexide-core/src/allocator.rs
- packages/vexide-core/src/backtrace.rs
- packages/vexide-core/src/competition.rs
- packages/vexide-core/src/float/mod.rs
- packages/vexide-core/src/fs/fs_str.rs
- packages/vexide-core/src/fs/mod.rs
- packages/vexide-core/src/io/mod.rs
- packages/vexide-core/src/os.rs
- packages/vexide-core/src/path.rs
- packages/vexide-core/src/program.rs
- packages/vexide-core/src/sync/mod.rs
- packages/vexide-core/src/sync/mutex.rs
- packages/vexide-core/src/time.rs
- packages/vexide-devices/src/adi/gyroscope.rs
- packages/vexide-devices/src/smart/serial.rs
- packages/vexide-macro/src/lib.rs
- packages/vexide-panic/src/lib.rs
- packages/vexide-startup/src/lib.rs
- packages/vexide/src/lib.rs
> refactor: flatten top-level modules in `vexide`

- CHANGELOG.md
- packages/vexide-core/src/lib.rs
> refactor: don't gate `vexide::allocator`

- CHANGELOG.md
- packages/vexide-async/src/lib.rs
- packages/vexide-core/src/allocator.rs
- packages/vexide-core/src/backtrace.rs
- packages/vexide-core/src/competition.rs
- packages/vexide-core/src/float/mod.rs
- packages/vexide-core/src/fs/fs_str.rs
- packages/vexide-core/src/fs/mod.rs
- packages/vexide-core/src/os.rs
- packages/vexide-core/src/path.rs
- packages/vexide-core/src/program.rs
- packages/vexide-panic/src/lib.rs
- packages/vexide/src/lib.rs
This PR also adds `vexide::program::abort` to match `std::process::abort`. Unlike `vexide::program::exit`, `abort` attempts to terminate the program as immediately as possible without doing any cleanup to the serial buffer.
> docs: document `vexide-core` more extensively, add `abort`

- CHANGELOG.md
- packages/vexide-core/Cargo.toml
- packages/vexide-core/src/lib.rs
- packages/vexide-startup/Cargo.toml
- packages/vexide-startup/src/lib.rs
- packages/vexide/Cargo.toml
- packages/vexide/src/lib.rs
Adds an `allocator` feature that allows using a custom allocator. This enables interfacing with C code that doesn't use the Rust allocator through `libc_alloc` and also just allows more flexibility.
- These are breaking changes for `default-features=false` users.
> feat: make `talc` an optional dependency

- CHANGELOG.md
- packages/vexide-core/src/fs/mod.rs
- packages/vexide-startup/src/patcher/overwriter_aeabi_memcpy.S
- Fixes `Metadata::len`
- Makes `File::tell` public and infallible (reasoning below)
- Refactors `overwriter_aeabi_memcpy.S` to reduce collisions with external impls
I made `File::tell` infallible (w/ a cautious debug assert) cause I'm assuming `vexFileTell` would only fail on an invalid `fd`, which we can guarantee is not the case.
Not yet fully tested due to lack of v5 brain on hand (and that it's 12.42am lol.
> Various small refactors and fixes

- packages/vexide-core/src/competition.rs
- packages/vexide-core/src/float/newlib.rs
- packages/vexide-core/src/fs/fs_str.rs
- packages/vexide-core/src/fs/mod.rs
- packages/vexide-devices/src/adi/motor.rs
- packages/vexide-devices/src/controller.rs
- packages/vexide-devices/src/peripherals.rs
- packages/vexide-devices/src/smart/ai_vision.rs
- packages/vexide-devices/src/smart/gps.rs
- packages/vexide-devices/src/smart/imu.rs
- packages/vexide-devices/src/smart/motor.rs
- packages/vexide-startup/src/patcher/mod.rs
Another flipped assertion logic error.
> fix: use correct assertion logic in AI vision id methods

- .vscode/settings.json
- packages/vexide-devices/src/adi/motor.rs
- packages/vexide-devices/src/adi/servo.rs
- packages/vexide-devices/src/peripherals.rs
- packages/vexide-devices/src/smart/ai_vision.rs
- packages/vexide-devices/src/smart/gps.rs
- packages/vexide-devices/src/smart/imu.rs
- packages/vexide-devices/src/smart/link.rs
- packages/vexide-devices/src/smart/motor.rs
- packages/vexide-devices/src/smart/rotation.rs
- packages/vexide-devices/src/smart/vision.rs
Fixes more of the assert!s for the AI Vision for the `set_color_code` and `color_code` methods. Also checks for more typos.
N/A
> fix: flip more assertion logics in ai vision and remove more typos

- CHANGELOG.md
- packages/vexide-devices/src/adi/digital.rs
This one tripped me up today. `AdiDigitalOut` and `AdiDigitalIn` both have an incorrect `is_low` implementation.
- I did not test this
- Technically semver major if [xkcd 1172](https://xkcd.com/1172/) is to be believed
> fix(devices): `AdiDigital*::is_low` shouldn't return `is_high`

- Cargo.toml
Adds the `default-members` field to the workspace so that `cargo build` has the behavior of `cargo build -p vexide`.
> chore: add default workspace members

- Cargo.toml
> fix: adjust `workspace.default-members` to allow building examples

- Cargo.toml
Reverts #322 which broke examples and #326 which broke rust-analyzer.
> fix: remove `workspace.default-members` for now

- CHANGELOG.md
- packages/vexide-devices/src/adi/addrled.rs
- packages/vexide-devices/src/adi/gyroscope.rs
- packages/vexide-devices/src/adi/motor.rs
- packages/vexide-devices/src/controller.rs
- packages/vexide-devices/src/display.rs
- packages/vexide-devices/src/lib.rs
- packages/vexide-devices/src/smart/ai_vision.rs
- packages/vexide-devices/src/smart/distance.rs
- packages/vexide-devices/src/smart/imu.rs
- packages/vexide-devices/src/smart/link.rs
- packages/vexide-devices/src/smart/motor.rs
- packages/vexide-devices/src/smart/serial.rs
- packages/vexide-devices/src/smart/vision.rs
Derives `#[derive(Debug, Clone, Copy, Eq, PartialEq, Snafu)]` for all error enums where possible. Closes #330
> refactor: consistent derives for error types

- CHANGELOG.md
- packages/vexide-devices/src/position.rs
- packages/vexide-devices/src/smart/rotation.rs
Matches the method name of other sensors.
> refactor: rename `RotationSensor::set_computation_interval` -> `RotationSensor::set_data_interval`

- CHANGELOG.md
- packages/vexide-devices/src/display.rs
I noticed that passing a stride value that wasn't equal to the rect size to `Display::draw_buffer` (a safe function) was dumping uninitialized memory to the screen -- technically a security bug (do I get a CVE?).
I also updated validation for src_stride to force it to be positive. However, I'm not sure whether this makes sense. It seems like the Display SDK doesn't handle it properly (?) so I just added an assert. See the pictures I sent in Discord.
- I did some testing on hardware
- This shouldn't be a breaking change
> fix(devices): validate draw_buffer stride properly

- packages/vexide-startup/src/lib.rs
- packages/vexide-startup/src/patcher/mod.rs
Fixes the patch magic check in `vexide_startup::_boot` from 0x1BDF to its correct value, 0xB1DF, using a named constant within the inline assembly.
> fix(boot): replace patch magic with named constant

- CHANGELOG.md
- packages/vexide-devices/src/display.rs
This PR ~~removes the unused color argument from `Display::erase` and documents the fact that the SDK uses the default background color instead.~~ fixes `Display::erase` to work as expected. It now fills a rectangle normally instead of using `vexDisplayErase` which does not take a background color.
- Not tested on a brain. _(edit: still not tested; I don't have hardware access until late October)_
- semver: ~~major~~ [patch](https://xkcd.com/1172/)
- ~~function argument removed~~
Fixes #349.
> fix: remove unused argument from `Display::erase`
