vexide/vexide

packages/vex-devices/src/controller.rs

This PR reimplements the controller API making use of only the vex-sdk crate.
Some slight breaking changes related to #[repr(u32)] on the controller id enum.

refactor: implement controllers in terms of vex-sdk

---

packages/vex-devices/Cargo.toml
packages/vex-devices/src/smart/imu.rs
packages/vex-devices/src/smart/vision.rs

Adds vision sensor API and refactors IMU to use `mint` types.

feat: Vision API, imu refactors

---

packages/vex-devices/Cargo.toml
packages/vex-devices/src/controller.rs
packages/vex-devices/src/screen.rs
packages/vex-devices/src/smart/imu.rs
packages/vex-devices/src/smart/link.rs
packages/vex-devices/src/smart/mod.rs
packages/vex-devices/src/smart/serial.rs

Initial (untested) generic serial and generic radio communications.

feat: VEXLink + Serial

---

packages/vexide-devices/src/controller.rs

Adds the `Controller::UPDATE_RATE` constant. Does what it says on the box.

feat: controller update rate constant

---

packages/vexide-async/Cargo.toml
packages/vexide-core/Cargo.toml
packages/vexide-devices/Cargo.toml
packages/vexide-math/Cargo.toml
packages/vexide-panic/Cargo.toml
packages/vexide/Cargo.toml

I don't feel like explaining myself right now

docs: add tropical to authors

---

packages/vexide-devices/src/smart/link.rs
packages/vexide-devices/src/smart/serial.rs

Removes a check that returns an `Err` if the buffer passed to `write` in generic serial or vexlink exceeds the available write bytes. According to `Write`, this shouldn't be done.
> It is not considered an error if the entire buffer could not be written to this writer.

fix: remove unnecessary serial/vexlink error checking

---

packages/vexide-devices/src/peripherals.rs

Seems like we forgot this when controller was implemented, so i'm just adding this here now.

feat: add controller to peripherals

---

packages/vexide-devices/src/controller.rs

Fixes a bug that prevents users from using controllers that are connected.

fix(controllers): allow using connected controllers

---

packages/vexide-graphics/Cargo.toml
packages/vexide-macro/Cargo.toml
packages/vexide-startup/Cargo.toml

This PR fixes issues with the crate manifests. These changes are published on crates.io and have been tested.

fix: update and fix all crate manifests 

---

packages/vexide-core/src/competition.rs

This allows users of `CompetitionBuilder` (not `Competition`, to maintain its simple API) to explicitly end the competition runtime and break out of the competition lifecycle by returning `ControlFlow::Break`.
Note that, unlike `Result`, `ControlFlow` does not imply error handling and it is very unlikely that a user would accidentally use it for error handling (which is usually incorrect).

feat(competition): allow tasks to explicity break out of the competition lifecycle

---

.github/workflows/rust.yml
packages/vexide-async/src/time.rs
packages/vexide-devices/src/adi/addrled.rs
packages/vexide-devices/src/position.rs
packages/vexide-devices/src/smart/motor.rs
packages/vexide-graphics/src/slint.rs
packages/vexide-startup/examples/booting.rs

This PR resolves all the CI errors and warnings.
- I haven't tested the motor tuning due to its possible hardware-damaging nature.

fix: resolve all CI errors and warnings

---

CHANGELOG.md

This fixes the changelog version

docs: update changelog version

---

packages/vexide-devices/src/adi/solenoid.rs

fix: correctly track logic level for `AdiSolenoid::toggle` function

---

CHANGELOG.md
packages/vexide-devices/src/controller.rs
packages/vexide/examples/clawbot.rs
packages/vexide/examples/smart_devices.rs

Discussed to an extent in #131.

refactor: make controller joysticks return `f64`

---

packages/vexide-async/Cargo.toml
packages/vexide-core/Cargo.toml
packages/vexide-devices/Cargo.toml
packages/vexide-graphics/Cargo.toml
packages/vexide-panic/Cargo.toml
packages/vexide-startup/Cargo.toml
packages/vexide/Cargo.toml

Updates vex-sdk to the latest version.

chore: update vex-sdk

---

README.md

This PR simply adds some missing link references in the README as well as fixes two typos.
This library looks great! I think I'll use it once I can convince my team. I love Rust and it would make my life so much easier to write in a modern programming language instead of C++.

chore: fix typos and links in readme

---

packages/vexide/Cargo.toml

chore: bump vexide version for real this time

---

CHANGELOG.md
packages/vexide-devices/src/battery.rs

- Resolved some TODOs by documenting units.
- Scales `current` and `voltage` to be in amps and volts respectively.

refactor: Battery API

---

packages/vexide-devices/src/smart/motor.rs

Fixes EXP motor support :3
We needed to wait for testing :skull:

fix: create exp motors with correct motor type

---

CHANGELOG.md

#175 didn't update changelog, so this PR does that.

chore: update changelog for #175

---

CHANGELOG.md
packages/vexide-core/src/program.rs
packages/vexide-devices/src/display.rs

Also updates some changelog things I missed in #155.

docs: fix inconsistencies in the `Display` docs

---

armv7a-vex-v5.json
packages/vexide-graphics/src/slint.rs

Wasn't caught by me since CI passed due to a CI skill issue. #205 fixes said skill issue.

fix: slint graphics driver

---

.github/workflows/rust.yml

fix: actually check if all features compile in check ci

---

packages/vexide-graphics/src/embedded_graphics.rs
packages/vexide-graphics/src/slint.rs

chore: lint vexide-graphics crate

---

.vscode/settings.json
README.md
examples/README.md
examples/sync.rs
packages/vexide/src/lib.rs

Will document all examples in the examples themselves and also in a new examples readme.

docs: document examples

---

CHANGELOG.md
packages/vexide-devices/src/smart/imu.rs

refactor: rename `InertialSensor::accel` to `InertialSensor::acceleration`

---

CHANGELOG.md
packages/vexide-devices/src/smart/optical.rs

Resolves the issues described in #214. Refactors `OpticalSensor::last_gesture`. Breaking change.

refactor: optical sensor gesture detection

---

CHANGELOG.md
packages/vexide-devices/src/controller.rs
packages/vexide-devices/src/smart/link.rs

refactor: rename NonTerminatingNul to Nul

---

CHANGELOG.md
Cargo.toml
packages/vexide-async/Cargo.toml
packages/vexide-core/Cargo.toml
packages/vexide-devices/Cargo.toml
packages/vexide-graphics/Cargo.toml
packages/vexide-macro/Cargo.toml
packages/vexide-panic/Cargo.toml
packages/vexide-startup/Cargo.toml
packages/vexide/Cargo.toml

chore: bump to v0.5.0-rc.1

---

CHANGELOG.md
packages/vexide-devices/src/smart/gps.rs
packages/vexide-devices/src/smart/imu.rs
packages/vexide-devices/src/smart/link.rs

This PR fixes a bug with IMU reset offsets being applied incorrectly.

fix: Correct imu and gps offset misadjustment

---

Cargo.toml
packages/vexide-async/Cargo.toml
packages/vexide-core/Cargo.toml
packages/vexide-devices/Cargo.toml
packages/vexide-graphics/Cargo.toml
packages/vexide-macro/Cargo.toml
packages/vexide-panic/Cargo.toml
packages/vexide-startup/Cargo.toml
packages/vexide-startup/src/banner/mod.rs
packages/vexide/Cargo.toml

chore: bump versions

---

CHANGELOG.md
Cargo.toml
packages/vexide-async/Cargo.toml
packages/vexide-core/Cargo.toml
packages/vexide-devices/Cargo.toml
packages/vexide-graphics/Cargo.toml
packages/vexide-panic/Cargo.toml
packages/vexide-startup/Cargo.toml
packages/vexide-startup/src/banner/mod.rs
packages/vexide/Cargo.toml

chore: bump to 0.5.1

---

.github/workflows/rust.yml
CHANGELOG.md
armv7a-vex-v5.json
flake.nix
packages/vexide-core/src/competition.rs
packages/vexide-core/src/sync/once.rs
packages/vexide-devices/src/controller.rs
packages/vexide-devices/src/position.rs
packages/vexide-devices/src/smart/imu.rs
packages/vexide-devices/src/smart/mod.rs
packages/vexide-devices/src/smart/optical.rs
rust-toolchain.toml

- Updates to `nightly-2024-12-06` (which has stabilized const float arithmetic).
- Makes all `Position` methods usable in const context.
- Bumps our MSRV to `1.82`.

feat: const `Position` methods

---

packages/vexide-devices/src/adi/digital.rs
packages/vexide-devices/src/adi/encoder.rs
packages/vexide-devices/src/adi/gyroscope.rs
packages/vexide-devices/src/adi/light_sensor.rs
packages/vexide-devices/src/adi/line_tracker.rs
packages/vexide-devices/src/adi/motor.rs
packages/vexide-devices/src/adi/potentiometer.rs
packages/vexide-devices/src/adi/pwm.rs
packages/vexide-devices/src/adi/range_finder.rs
packages/vexide-devices/src/adi/servo.rs

I had some time and did the not-fun work of adding examples. Hopefully they compile; it doesn't seem like there's a way to `cargo check` doctests yet.

docs: Add examples for all the adi devices

---

armv7a-vex-v5.json
packages/vexide-core/src/fs/mod.rs

fix: `c_char` definition change in latest nightly

---

CHANGELOG.md
packages/vexide-devices/src/smart/motor.rs

Closes #259 
Do not merge until hardware tested.

fix: set motor position in ticks

---

CHANGELOG.md
packages/vexide-core/src/fs/mod.rs

Needs hardware testing, but I'm pretty sure these changes are fine.

fix: negative file seeking with `SeekFrom::End`

---

packages/vexide-panic/src/lib.rs

Fix of #274 review comment.
I haven't tested this. I haven't even used any VEX products for the past 3 days. ~~I haven't run CI.~~ I haven't run `cargo check`.

chore(panic): revise error message that shouldn't happen

---

flake.lock
flake.nix

build: update flake lock and add llvm-bintools to devShell

---

CHANGELOG.md
Cargo.toml
packages/vexide-async/Cargo.toml
packages/vexide-core/Cargo.toml
packages/vexide-devices/Cargo.toml
packages/vexide-graphics/Cargo.toml
packages/vexide-panic/Cargo.toml
packages/vexide-startup/Cargo.toml
packages/vexide-startup/src/banner/mod.rs
packages/vexide/Cargo.toml

chore: bump crate versions

---

CHANGELOG.md
Cargo.toml
packages/vexide-graphics/Cargo.toml
packages/vexide-startup/Cargo.toml
packages/vexide-startup/src/banner/mod.rs
packages/vexide-startup/src/lib.rs
packages/vexide/Cargo.toml

chore: bump to 0.6.1

---

CHANGELOG.md
examples/fs.rs
packages/vexide-core/src/fs/fs_str.rs
packages/vexide-core/src/fs/mod.rs
packages/vexide-core/src/path.rs

- I have tested these changes on a VEX V5 Brain.

feat: dir reading

---

CHANGELOG.md
packages/vexide-devices/src/controller.rs

fix: correct flipped controller assert logic

---

.github/workflows/rust.yml
flake.nix
packages/vexide-core/src/fs/mod.rs
packages/vexide-panic/src/lib.rs
rust-toolchain.toml

they changed `c_char` again or something

chore: update toolchain to `nightly-2025-02-18`

---

CHANGELOG.md
packages/vexide-core/src/fs/fs_str.rs
packages/vexide-core/src/fs/mod.rs
packages/vexide-devices/src/adi/gyroscope.rs
packages/vexide-devices/src/display.rs
packages/vexide-devices/src/peripherals.rs
packages/vexide-devices/src/smart/imu.rs
packages/vexide-macro/src/lib.rs

Resolves some lints by stablizing some more APIs in `const` context.

fix: resolve lints

---

CHANGELOG.md
packages/vexide-devices/src/smart/gps.rs
packages/vexide-devices/src/smart/mod.rs

Refactors the GPS api to be more sensible, given the knowledge I have about the sensor now. This removes the separate `GpsImu` struct an integrates everything into a single type. Documentation has also been greatly improved in this area too.

refactor: unified GPS API

---

packages/vexide-startup/src/lib.rs

Closes #290.
Needs to be extensively tested before merge.

feat: reclaim patcher memory as heap space

---

CHANGELOG.md
Cargo.toml
packages/vexide-async/Cargo.toml
packages/vexide-core/Cargo.toml
packages/vexide-devices/Cargo.toml
packages/vexide-macro/Cargo.toml
packages/vexide-panic/Cargo.toml
packages/vexide-startup/Cargo.toml
packages/vexide-startup/src/banner/mod.rs
packages/vexide/Cargo.toml

chore: bump to 0.7.0

---

packages/vexide-devices/src/controller.rs

fix: use 1-indexed lines and columns for controller screen in the examples. 

---

packages/vexide-async/src/reactor.rs
packages/vexide-async/src/time.rs

perf: :zap: Reduce unnecessary sleeper polls

---

CHANGELOG.md
examples/README.md
examples/task_local_storage.rs
packages/vexide-async/src/executor.rs
packages/vexide-async/src/lib.rs
packages/vexide-async/src/local.rs
packages/vexide-async/src/task.rs
packages/vexide-startup/link/v5.ld

This adds task-local variables

feat: add task-local storage
